"""
EDA Part 2 — Labels, Correlations & Temporal Analysis
Generates publication-ready figures from MIMIC-III for the project report.

Figures produced (saved to output/eda/):
  8.  Label prevalence / class imbalance
  9.  Feature correlation heatmap
  10. Missing data analysis
  11. Mortality by age group
  12. Temporal vital trends (survivors vs non-survivors)
  13. Admission type distribution

Usage:
    python eda_part2.py [--sample N]

Requires: output/feature_cache_y.npy and output/feature_cache_meta.pkl
          (generated by main_pipeline.py)
"""

import os
import sys
import argparse
import pickle
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from tqdm import tqdm
import logging

from data_loader import MIMICDataLoader

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

sns.set_theme(style='whitegrid', font_scale=1.1)
plt.rcParams.update({
    'figure.dpi': 300,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'font.family': 'sans-serif',
    'axes.titleweight': 'bold',
    'axes.titlesize': 14,
    'axes.labelsize': 12,
})

COLOR_SURV = '#2196F3'
COLOR_DEAD = '#F44336'
OUTPUT_DIR = os.path.join('output', 'eda')


def ensure_dir():
    os.makedirs(OUTPUT_DIR, exist_ok=True)


# ═══════════════════════════════════════════════════════════════════════════════
#  FIGURE 8 — Label Prevalence (Class Imbalance)
# ═══════════════════════════════════════════════════════════════════════════════

def fig_label_prevalence():
    """Bar chart showing positive rate for all 19 prediction labels."""
    logger.info("Figure 8: Label prevalence / class imbalance")

    y_path = os.path.join('output', 'feature_cache_y.npy')
    meta_path = os.path.join('output', 'feature_cache_meta.pkl')

    if not os.path.exists(y_path) or not os.path.exists(meta_path):
        logger.warning("  Feature cache not found — skipping label prevalence")
        return

    y = np.load(y_path)
    with open(meta_path, 'rb') as f:
        meta = pickle.load(f)
    label_names = meta['label_names']

    pos_rates = (y > 0.5).mean(axis=0) * 100

    # Sort by positive rate
    order = np.argsort(pos_rates)[::-1]

    fig, ax = plt.subplots(figsize=(14, 7))

    # Color by severity: red if <5%, orange if <15%, green otherwise
    colors = []
    for rate in pos_rates[order]:
        if rate < 5:
            colors.append('#F44336')
        elif rate < 15:
            colors.append('#FF9800')
        else:
            colors.append('#4CAF50')

    names = [label_names[i] for i in order]
    bars = ax.barh(range(len(names)), pos_rates[order], color=colors,
                   edgecolor='white', height=0.7)

    ax.set_yticks(range(len(names)))
    ax.set_yticklabels(names, fontsize=10)
    ax.set_xlabel('Positive Class Rate (%)')
    ax.set_title('Prediction Label Prevalence — Class Imbalance Analysis',
                 fontsize=14, fontweight='bold')
    ax.invert_yaxis()

    # Add percentage labels
    for i, (bar, rate) in enumerate(zip(bars, pos_rates[order])):
        ratio = 100 / rate - 1 if rate > 0 else float('inf')
        ratio_str = f'1:{ratio:.0f}' if ratio < 1000 else 'extreme'
        ax.text(bar.get_width() + 0.3, bar.get_y() + bar.get_height()/2,
                f' {rate:.1f}%  ({ratio_str})',
                va='center', fontsize=9)

    # Legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#F44336', label='Severe imbalance (<5%)'),
        Patch(facecolor='#FF9800', label='Moderate imbalance (5-15%)'),
        Patch(facecolor='#4CAF50', label='Manageable (>15%)'),
    ]
    ax.legend(handles=legend_elements, loc='lower right', fontsize=10)

    plt.tight_layout()
    path = os.path.join(OUTPUT_DIR, 'eda_label_prevalence.png')
    plt.savefig(path)
    plt.close()
    logger.info(f"  → {path}")


# ═══════════════════════════════════════════════════════════════════════════════
#  FIGURE 9 — Correlation Heatmap
# ═══════════════════════════════════════════════════════════════════════════════

def fig_correlation_heatmap():
    """Feature-feature correlation from cached features."""
    logger.info("Figure 9: Correlation heatmap")

    x_path = os.path.join('output', 'feature_cache_X.npy')
    if not os.path.exists(x_path):
        logger.warning("  Feature cache X not found — skipping correlation")
        return

    # Load with mmap and sample for speed
    X = np.load(x_path, mmap_mode='r')
    n_samples = min(10000, X.shape[0])
    idx = np.random.choice(X.shape[0], n_samples, replace=False)

    # Average across time steps to get [samples × features]
    X_avg = np.nanmean(X[idx], axis=1)
    n_feat = X_avg.shape[1]

    # Only show first 20 features for readability
    n_show = min(20, n_feat)
    X_sub = X_avg[:, :n_show]

    # Feature names (approximate — from config order)
    feat_names = [
        'HR_mean', 'HR_std', 'HR_min', 'HR_max', 'HR_trend',
        'SBP_mean', 'SBP_std', 'SBP_min', 'SBP_max', 'SBP_trend',
        'DBP_mean', 'DBP_std', 'DBP_min', 'DBP_max', 'DBP_trend',
        'MAP_mean', 'MAP_std', 'MAP_min', 'MAP_max', 'MAP_trend',
    ][:n_show]

    corr = np.corrcoef(X_sub.T)
    np.fill_diagonal(corr, 1.0)  # ensure diagonal is exactly 1

    fig, ax = plt.subplots(figsize=(12, 10))
    mask = np.triu(np.ones_like(corr, dtype=bool), k=1)

    sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='RdBu_r',
                center=0, vmin=-1, vmax=1,
                xticklabels=feat_names, yticklabels=feat_names,
                square=True, linewidths=0.5, ax=ax,
                annot_kws={'size': 7},
                cbar_kws={'label': 'Pearson Correlation', 'shrink': 0.8})

    ax.set_title('Feature Correlation Heatmap (First 20 Features)',
                 fontsize=14, fontweight='bold')
    plt.xticks(rotation=45, ha='right', fontsize=9)
    plt.yticks(fontsize=9)

    plt.tight_layout()
    path = os.path.join(OUTPUT_DIR, 'eda_correlation_heatmap.png')
    plt.savefig(path)
    plt.close()
    logger.info(f"  → {path}")


# ═══════════════════════════════════════════════════════════════════════════════
#  FIGURE 10 — Missing Data Analysis
# ═══════════════════════════════════════════════════════════════════════════════

def fig_missingness(loader: MIMICDataLoader, sample_n=3000):
    """Bar chart showing % missing per vital/lab feature."""
    logger.info(f"Figure 10: Missing data analysis (sampling {sample_n} stays)")

    if loader.icu_stays is None or len(loader.icu_stays) == 0:
        logger.warning("  No ICU stays, skipping")
        return

    vital_itemids = {
        'Heart Rate': [220045, 211],
        'Systolic BP': [220050, 220179, 51, 455],
        'Diastolic BP': [220051, 220180, 8368, 8441],
        'Mean ABP': [220052, 220181, 52, 456],
        'Resp Rate': [220210, 224690, 618, 615],
        'SpO₂': [220277, 646],
        'Temperature': [223761, 223762, 676, 678],
        'Glucose (chart)': [220621, 226537, 807, 811, 1529],
    }

    lab_keywords = {
        'Creatinine': 'creatinine',
        'Lactate': 'lactate',
        'WBC': 'wbc',
        'Hemoglobin': 'hemoglobin',
        'Platelets': 'platelet',
        'Bicarbonate': 'bicarbonate',
        'Chloride': 'chloride',
    }

    lab_itemids = {}
    if loader.d_labitems is not None:
        for name, kw in lab_keywords.items():
            mask = loader.d_labitems['label'].str.lower().str.contains(kw, na=False)
            ids = loader.d_labitems[mask]['itemid'].unique().tolist()
            if ids:
                lab_itemids[name] = ids

    # Sample ICU stays
    all_stays = loader.icu_stays['icustay_id'].unique()
    if len(all_stays) > sample_n:
        sampled_stays = np.random.choice(all_stays, sample_n, replace=False)
    else:
        sampled_stays = all_stays

    # Count stays with at least one reading per feature
    missing_pct = {}

    if loader.chartevents is not None and len(loader.chartevents) > 0:
        charts_sampled = loader.chartevents[
            loader.chartevents['icustay_id'].isin(sampled_stays)
        ]
        for name, ids in vital_itemids.items():
            stays_with = charts_sampled[charts_sampled['itemid'].isin(ids)]['icustay_id'].nunique()
            missing_pct[name] = (1 - stays_with / len(sampled_stays)) * 100

    if loader.labevents is not None and len(loader.labevents) > 0:
        labs_sampled = loader.labevents[
            loader.labevents['icustay_id'].isin(sampled_stays)
        ]
        for name, ids in lab_itemids.items():
            stays_with = labs_sampled[labs_sampled['itemid'].isin(ids)]['icustay_id'].nunique()
            missing_pct[name] = (1 - stays_with / len(sampled_stays)) * 100

    if not missing_pct:
        logger.warning("  No missingness data")
        return

    # Sort by missingness
    sorted_items = sorted(missing_pct.items(), key=lambda x: x[1], reverse=True)
    names = [x[0] for x in sorted_items]
    values = [x[1] for x in sorted_items]

    fig, ax = plt.subplots(figsize=(12, 7))

    colors = ['#F44336' if v > 50 else '#FF9800' if v > 20 else '#4CAF50' for v in values]
    bars = ax.barh(range(len(names)), values, color=colors, edgecolor='white', height=0.6)

    ax.set_yticks(range(len(names)))
    ax.set_yticklabels(names, fontsize=11)
    ax.set_xlabel('% of ICU Stays Missing This Feature')
    ax.set_title(f'Feature Missingness Analysis (n={len(sampled_stays):,} stays)',
                 fontsize=14, fontweight='bold')
    ax.invert_yaxis()
    ax.set_xlim(0, 105)

    for bar, val in zip(bars, values):
        ax.text(bar.get_width() + 0.8, bar.get_y() + bar.get_height()/2,
                f'{val:.1f}%', va='center', fontsize=10)

    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#F44336', label='High missingness (>50%)'),
        Patch(facecolor='#FF9800', label='Moderate (20-50%)'),
        Patch(facecolor='#4CAF50', label='Low (<20%)'),
    ]
    ax.legend(handles=legend_elements, loc='lower right')

    plt.tight_layout()
    path = os.path.join(OUTPUT_DIR, 'eda_missingness.png')
    plt.savefig(path)
    plt.close()
    logger.info(f"  → {path}")


# ═══════════════════════════════════════════════════════════════════════════════
#  FIGURE 11 — Mortality by Age Group
# ═══════════════════════════════════════════════════════════════════════════════

def fig_mortality_by_age(merged: pd.DataFrame):
    """Grouped bar: mortality rate by age decile."""
    logger.info("Figure 11: Mortality by age group")

    df = merged[['age', 'expire_flag']].dropna().copy()
    bins = [0, 30, 40, 50, 60, 70, 80, 100]
    labels = ['<30', '30-39', '40-49', '50-59', '60-69', '70-79', '80+']
    df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)

    stats = df.groupby('age_group', observed=True).agg(
        count=('expire_flag', 'count'),
        deaths=('expire_flag', 'sum'),
        mortality=('expire_flag', 'mean'),
    ).reset_index()
    stats['mortality_pct'] = stats['mortality'] * 100

    fig, ax1 = plt.subplots(figsize=(10, 6))

    x = range(len(stats))
    bars = ax1.bar(x, stats['count'], color='#42A5F5', alpha=0.8,
                   edgecolor='white', width=0.6, label='ICU Stays', zorder=3)

    ax1.set_xlabel('Age Group', fontsize=12)
    ax1.set_ylabel('Number of ICU Stays', fontsize=12)
    ax1.set_xticks(x)
    ax1.set_xticklabels(stats['age_group'], fontsize=11)

    # Mortality overlay
    ax2 = ax1.twinx()
    ax2.plot(x, stats['mortality_pct'], 'o-', color='#F44336',
             linewidth=2.5, markersize=8, label='Mortality Rate', zorder=5)
    ax2.set_ylabel('Mortality Rate (%)', color='#F44336', fontsize=12)
    ax2.tick_params(axis='y', labelcolor='#F44336')

    # Annotate mortality percentages
    for xi, mort in zip(x, stats['mortality_pct']):
        ax2.annotate(f'{mort:.1f}%', (xi, mort),
                     textcoords='offset points', xytext=(0, 12),
                     ha='center', fontsize=10, fontweight='bold', color='#D32F2F')

    ax1.set_title('Mortality Rate by Age Group', fontsize=14, fontweight='bold')

    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left')

    plt.tight_layout()
    path = os.path.join(OUTPUT_DIR, 'eda_mortality_by_age.png')
    plt.savefig(path)
    plt.close()
    logger.info(f"  → {path}")


# ═══════════════════════════════════════════════════════════════════════════════
#  FIGURE 12 — Temporal Vital Trends
# ═══════════════════════════════════════════════════════════════════════════════

def fig_temporal_vitals(loader: MIMICDataLoader, merged: pd.DataFrame, sample_n=2000):
    """Line plots of mean vitals over first 48h: survivors vs non-survivors."""
    logger.info(f"Figure 12: Temporal vital trends (sampling {sample_n} stays)")

    if loader.chartevents is None or len(loader.chartevents) == 0:
        logger.warning("  No chartevents, skipping")
        return

    vitals_to_plot = {
        'Heart Rate': [220045, 211],
        'Mean ABP': [220052, 220181, 52, 456],
        'SpO₂ (%)': [220277, 646],
        'Resp Rate': [220210, 224690, 618, 615],
    }

    # Sample stays, balanced between survivors/deceased
    deceased = merged[merged['expire_flag'] == 1]['icustay_id'].values
    survived = merged[merged['expire_flag'] == 0]['icustay_id'].values

    n_each = min(sample_n // 2, len(deceased), len(survived))
    sampled_dead = np.random.choice(deceased, n_each, replace=False)
    sampled_surv = np.random.choice(survived, n_each, replace=False)
    all_sampled = np.concatenate([sampled_dead, sampled_surv])

    charts = loader.chartevents[loader.chartevents['icustay_id'].isin(all_sampled)].copy()

    # Merge intime for relative time
    intime_map = merged.set_index('icustay_id')['intime'].to_dict()
    expire_map = merged.set_index('icustay_id')['expire_flag'].to_dict()

    charts['intime'] = charts['icustay_id'].map(intime_map)
    charts['expire_flag'] = charts['icustay_id'].map(expire_map)
    charts['hours_since_admit'] = (
        (charts['charttime'] - charts['intime']).dt.total_seconds() / 3600
    )

    # Filter to first 48 hours
    charts = charts[(charts['hours_since_admit'] >= 0) & (charts['hours_since_admit'] <= 48)]

    # Bin into 2-hour windows
    charts['hour_bin'] = (charts['hours_since_admit'] // 2) * 2

    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes = axes.flatten()

    for i, (name, ids) in enumerate(vitals_to_plot.items()):
        ax = axes[i]
        subset = charts[charts['itemid'].isin(ids)].copy()

        if len(subset) == 0:
            ax.text(0.5, 0.5, 'No data', transform=ax.transAxes, ha='center')
            ax.set_title(name)
            continue

        for label, flag, color in [('Survived', 0, COLOR_SURV), ('Deceased', 1, COLOR_DEAD)]:
            grp = subset[subset['expire_flag'] == flag]
            if len(grp) == 0:
                continue
            hourly = grp.groupby('hour_bin')['valuenum'].agg(['mean', 'std']).reset_index()

            ax.plot(hourly['hour_bin'], hourly['mean'], '-', color=color,
                    linewidth=2, label=label)
            ax.fill_between(hourly['hour_bin'],
                            hourly['mean'] - hourly['std'] * 0.5,
                            hourly['mean'] + hourly['std'] * 0.5,
                            alpha=0.15, color=color)

        ax.set_xlabel('Hours Since ICU Admission')
        ax.set_ylabel(name)
        ax.set_title(f'{name}: First 48 Hours', fontweight='bold')
        ax.legend(fontsize=10)
        ax.set_xlim(0, 48)
        ax.grid(alpha=0.3)

    plt.suptitle('Temporal Vital Sign Trends: Survivors vs Deceased',
                 fontsize=16, fontweight='bold', y=1.01)
    plt.tight_layout()
    path = os.path.join(OUTPUT_DIR, 'eda_temporal_vitals.png')
    plt.savefig(path)
    plt.close()
    logger.info(f"  → {path}")


# ═══════════════════════════════════════════════════════════════════════════════
#  FIGURE 13 — Admission Type Distribution
# ═══════════════════════════════════════════════════════════════════════════════

def fig_admission_types(merged: pd.DataFrame):
    """Bar chart of admission types with mortality overlay."""
    logger.info("Figure 13: Admission type distribution")

    if 'admission_type' not in merged.columns:
        logger.warning("  No admission_type column, skipping")
        return

    stats = merged.groupby('admission_type').agg(
        count=('subject_id', 'count'),
        mortality=('expire_flag', 'mean'),
    ).reset_index()
    stats['mortality_pct'] = stats['mortality'] * 100
    stats = stats.sort_values('count', ascending=False)

    fig, ax1 = plt.subplots(figsize=(10, 6))

    colors = sns.color_palette('Set2', len(stats))
    bars = ax1.bar(range(len(stats)), stats['count'], color=colors,
                   edgecolor='white', width=0.6, zorder=3)

    ax1.set_xticks(range(len(stats)))
    ax1.set_xticklabels(stats['admission_type'], fontsize=11, rotation=15, ha='right')
    ax1.set_ylabel('Number of ICU Stays')

    for bar, count in zip(bars, stats['count']):
        ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 100,
                 f'{count:,}', ha='center', va='bottom', fontweight='bold', fontsize=10)

    ax2 = ax1.twinx()
    ax2.plot(range(len(stats)), stats['mortality_pct'],
             'D-', color='#F44336', markersize=10, linewidth=2, label='Mortality Rate')
    ax2.set_ylabel('Mortality Rate (%)', color='#F44336')
    ax2.tick_params(axis='y', labelcolor='#F44336')
    ax2.set_ylim(0, max(stats['mortality_pct']) * 1.4)

    for xi, mort in zip(range(len(stats)), stats['mortality_pct']):
        ax2.annotate(f'{mort:.1f}%', (xi, mort),
                     textcoords='offset points', xytext=(0, 10),
                     ha='center', fontsize=10, fontweight='bold', color='#D32F2F')

    ax1.set_title('Admission Type Distribution with Mortality Rate',
                  fontsize=14, fontweight='bold')
    ax2.legend(loc='upper right')

    plt.tight_layout()
    path = os.path.join(OUTPUT_DIR, 'eda_admission_types.png')
    plt.savefig(path)
    plt.close()
    logger.info(f"  → {path}")


# ═══════════════════════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description='EDA Part 2: Labels, Correlations & Temporal')
    parser.add_argument('--sample', type=int, default=3000,
                        help='Number of ICU stays to sample for temporal analysis (default: 3000)')
    args = parser.parse_args()

    ensure_dir()

    print("=" * 60)
    print("  EDA PART 2 — Labels, Correlations & Temporal")
    print("=" * 60)

    # Load data
    print("\nLoading MIMIC-III data...")
    loader = MIMICDataLoader('data', 'config.yaml')
    merged = loader.merge_data()
    print(f"✓ Loaded {len(merged):,} ICU stays\n")

    # Figures that use cached labels (no data reload needed)
    fig_label_prevalence()
    fig_correlation_heatmap()

    # Figures that use loaded data
    fig_missingness(loader, sample_n=args.sample)
    fig_mortality_by_age(merged)
    fig_temporal_vitals(loader, merged, sample_n=args.sample)
    fig_admission_types(merged)

    print(f"\n✅ Part 2 complete — 6 figures saved to {OUTPUT_DIR}/")


if __name__ == '__main__':
    main()
